import type { Metadata } from "next";
import "./globals.css";

import { Licorice } from "next/font/google";
const licorice = Licorice({
	variable: "--font-licorice",
	weight: "400",
	subsets: ["latin"],
});
import { DM_Serif_Display } from "next/font/google";
const DMSerif = DM_Serif_Display({
	variable: "--font-dmserif",
	weight: "400",
	subsets: ["latin"],
});
import { DM_Sans } from "next/font/google";
const DMSans = DM_Sans({
	variable: "--font-dmsans",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${licorice.variable} ${DMSerif.variable} ${DMSans.variable}`}>{children}</body>
    </html>
  );
}
