// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  landing: dynamic(() => import("./Landing")),
  recipe_card: dynamic(() => import("./RecipeCard")),
  selected_recipes: dynamic(() => import("./SelectedRecipes")),
};
